app.ts, assets.ts, button.ts, camera.ts, character.ts, characters.ts, component.ts, cursor.ts, extras.ts, kelpie.ts, kodeStage.ts, language.ts, library.ts, main.ts, menu.ts, physics.ts, program.ts, pxt.json, stage.ts, vec2.ts, worldStage.ts
* namespace rename to kojac.
* update pxt version to beta.
* tweak cursor speed.
=> namespace rename

editor.ts, jacs_topwriter.ts, language.ts
Editor is quite generic with respect to different tile types, but there's lots of duplicated code with respect to sensors/actuators/filters/modifiers.
=> Editor refactor

assets.ts, language.ts, tiles.ts
@tballmsft with the `accelEvent.iconOverride = icon` when you I add a filter to accel event, the whole rendering is messed up - the tiles are drawn over each other; any idea why?
also, I can't go back to home screen to save the program and deploy it...
=> add accel events and iconOverride

editor.ts, navigator.ts
=> Access navigator

home.ts
Added two samples with buttons to home screen
=> Basic samples added, flashing heart and smile buttons

editor.ts
Fix for https://github.com/microsoft/microcode/issues/135
=> move page icon to left, remove left right

editor.ts, navigator.ts, picker.ts
Added `SimpleGridNavigator`, a brute-force grid, and set it as the picker's default navigator.
=> Add simple grid navigator

navigator.ts
Vertical nav: if no good option, go with the least bad option
=> more flexible vertical navigation

cursor.ts
@pelikhan excited to start contributing!
This PR will fix [https://github.com/microsoft/microcode/issues/160](url)
The two screenshots below are after I made my changes.
=> changed ariaToolTip based on size

button.ts, editor.ts, language.ts, math.ts, options.ts, scene.ts, screen.ts, sprite.ts, tiles.ts
Baseline 1.2.3: rock paper scissors, 9.5fps, 5.4fps with led editor
- drop shadow on tiles: 2fps
- drop bounds checking on all sprites: 2fps
=> a few perf improvements

accessibility.ts, assets.ts, jacs_format.ts, jacs_opwriter.ts, jacs_stringify.ts, jacs_topwriter.ts, language.ts, locales/fr/strings.json, locales/strings.json, tiles.ts
We'll need group to do radio in classrooms.
=> radio set group

docs.ts, editor.ts, screen.ts
I've been trying to render the entire sample on an image but I can't somehow relayout the page/reset buttons. any ideas?
=> attempt at rendering entire samples

assets.ts, jacs_topwriter.ts, language.ts, tiles.ts
Tile takes number from 0/12 to 6, mapped on the circle as hours (e.g. multiply by 30 % #60)
=> Servo tile support

cursorscene.ts, docs/manual.md, editor.ts, keymap.ts
=> Player 2 keys

jacs_topwriter.ts, language.ts, tiles.ts
Not used anywhere, just wasting memory.
=> removing unused tile name

accessibility.ts, assets/js/custom.js, button.ts, cursor.ts, cursorscene.ts, editor.ts, navigator.ts, pointerevents.ts, scene.ts
support for mouse hovering by moving tooltip
=> Mouse hover

jacs_bytecode.ts, jacs_format.ts, jacs_opwriter.ts, jacs_stringify.ts, jacs_topwriter.ts, pxt.json
seems to work with all samples
=> update to new RPN bytecode format

assets/index.html, config.ts, docs.ts, home.ts, index.html, mkc.json, pxt.json
Preparing for larger sim area.
=> Larger sim area

cursor.ts, docs.ts, options.ts, scene.ts, screen.ts
- Removed extra screen image
- adding profiling calls
=> memory: don't use 2 images for double buffer

accessibility.ts, assets.ts, assets/js/custom.js, jacs_topwriter.ts, language.ts, locales/fr/strings.json, locales/strings.json, tiles.ts
Support for explicity page start tile
- missing: jacscript compilation
=> page start tile

assets.ts, docs/manual.md, editor.ts, keymap.ts
Page Up/ Page Down, [] to navigate between pages.
=> page bindings

.gitignore, docs/develop.md, scripts/setup-jekyll.sh
dev environment to build jekyll locally
=> Jekyll local

accessibility.ts, home.ts, scripts/lochex.mjs, tooltips.ts
=> encode tooltips as function

math.ts
=> removing dirty field in vec2

docs/robot.md, robot/blocks.ts, robot/pxt.json, robot/robotdriver.ts, robot/storage.cpp, robot/storage.ts, robot/test.ts
storing radio and drift in flash
=> persistent calibration

robot/robotdriver.ts
Improve reliability and send 2 messages at a time.
- testing on hardware
=> send 2 radio messages every messages

editor.ts, jacs_topwriter.ts, picker.ts
Fix for https://github.com/microsoft/microcode/issues/459
=> stop running in a picker

robot/robotdriver.ts
Emit wall events for every intermediate values. Eg. 5 -> 1, will emit 5,4,3,2,1
=> Wall events

assets.ts, docs.ts, locales/tooltips.json, robot/protocol.ts, robot/robotdriver.ts, tids.ts, tiles.ts
@tballmsft did i get the plumbing right?
=> add led off support

robot/blocks.ts, robot/kittenbotminilfr.ts, robot/maindfrobotmaqueen.ts, robot/maindfrobotmaqueenplusv2.ts, robot/mainelecfreakscutebot.ts, robot/mainelecfreakscutebotpro.ts, robot/mainkeystudiominismartrobot.ts, robot/mainkittenbotminilfr.ts, robot/mainkittenbotnanobit.ts, robot/mainkittenbotrobotbit.ts, robot/mainyahboomtinybit.ts, robot/protocol.ts, robot/pxt.json, robot/radio.ts, robot/remoterobot.ts, robot/robot.ts, robot/robotdriver.ts, robot/test.ts
drop parseInt, split to reduce minilfr size
=> Radio tree shake

robot/kittenbotnanobit.ts
1. add arm to nanobit robot
2. fix motor mapping according to instruction mannual
=> fixes for nanobit robot
